### ISSUE TITLE
Error when specifying palette options in .Rprofile

### ISSUE THREAD

**Issue by mattwarkentin** [MilesMcBain/paint#1] opened 2021-08-06 15:25 UTC
Hi @MilesMcBain,

Fun package! I have been playing around with it a little but when I tried to set a palette in my `.Rprofile` file I end up getting an error when I boot up an `R` session. Thoughts?
```
options(paint_palette = paint::brewer_set3_12())
```
```
Error in rgb(c(141, 255, 190, 251, 128, 253, 179, 252, 217, 188, 204,  :
  could not find function "rgb"
```

**Comment by MilesMcBain** [comment] 2021-08-06 23:41
Thanks for the report!

I couldn't reproduce this one. It's a bit of a surprise because that is bubbling up from inside `{crayon}`. This function is `grDevices::rgb`.

Maybe you have an old version of either of these packages that is missing this function? Does:

```
install.packages(c("crayon, "grDevices"))
```

fix it?

**Comment by MilesMcBain** [comment] 2021-08-07 03:28
Sorry I did reproduce this! Environment weirdness during Rprofile exec. Can be fixed with some hacks.

**Comment by MilesMcBain** [comment] 2021-08-07 07:38
Hacks deployed, seems to work now. Let me know if it doesn't fix this for you @mattwarkentin. Thanks!

**Closed** 2021-08-07 07:37 UTC

**Comment by mattwarkentin** [comment] 2021-08-07 21:46
Phew! I'm thankful my issue wasn't just me having outdated dependencies, haha!

Everything seems to be working great.
